
### Login
@baseUrl = http://localhost:3000/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXN1YXJpbyI6IkVkdWFyZG8gNDY1IiwiZW1haWwiOiJoaWFzZDEyZUBnbWFpbC5jb20iLCJyb2xfaWQiOjIsImFjdGl2byI6MSwiaWF0IjoxNzc2NDc2NTA2LCJleHAiOjE3NzkwNjg1MDZ9.p_lBrJoAMOuJLjHhsRrzkEvfXPdno01VYCgtWD1FFZo
### Login con usuario
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "username": "Eduardo 465",
    "password": "Eduardog46500!"
}

### Login con email
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "hiasd12e@gmail.com",
    "password": "Eduardog46500!"
}

### Register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "user": {
        "username": "eduardo_465",
        "email": "eduardo1@ejemplo.com",
        "password": "Eduardog46500!"
    },
    "perfilUser": {
        "firstName": "Eduardo",
        "lastName": "García",
        "birthDate": "1999-05-15",
        "phone": "5512345678"
    }
}

### Cambiar contraseña (con usuario)
PUT {{baseUrl}}/auth/cambiar-contrasena
Content-Type: application/json

{
    "username": "Eduardo 465",
    "password": "Eduardog46500!",
    "newPassword": "NuevaContrasena123!"
}

### Cambiar contraseña (con email)
PUT {{baseUrl}}/auth/cambiar-contrasena
Content-Type: application/json

{
    "email": "eduardo@ejemplo.com",
    "password": "Eduardog46500!",
    "newPassword": "NuevaContrasena123!"
}

### Logout
POST {{baseUrl}}/auth/logout