### ─── LOGS ───────────────────────────────────────────────────────────────────
@base = http://localhost:3000/api/logs
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXN1YXJpbyI6IkVkdWFyZG8gNDY1IiwiZW1haWwiOiJoaWFzZDEyZUBnbWFpbC5jb20iLCJyb2wiOiJBZG1pbmlzdHJhZG9yIiwiYWN0aXZvIjoxLCJpYXQiOjE3NzY0MjM2MzIsImV4cCI6MTc3OTAxNTYzMn0.SKnwwkGf_PvO8tQDssG32D9zLkRPoDRvbUIgZHmJKdM
### Obtener todos los logs
GET {{base}}/
Cookie: token={{token}}

### Obtener log por ID
GET {{base}}/10
Cookie: token={{token}}

### Obtener logs por usuario
GET {{base}}/user/1
Cookie: token={{token}}

### Obtener logs por fecha (YYYY-MM-DD)
GET {{base}}/date/2026-04-17
Cookie: token={{token}}

### Obtener logs por nivel (error | warn | info | http | sql)
GET {{base}}/level/error
Cookie: token={{token}}

### Obtener logs por ruta
GET {{base}}/path?path=/api/auth/login
Cookie: token={{token}}

### Obtener logs por rango de fechas
GET {{base}}/rango?startDate=2026-04-01&endDate=2026-04-17
Cookie: token={{token}}

### Obtener logs por status code
GET {{base}}/status/500
Cookie: token={{token}}

### Obtener estadísticas
GET {{base}}/stats
Cookie: token={{token}}

### ─── DELETE ──────────────────────────────────────────────────────────────────

### Eliminar log por ID
DELETE {{base}}/9
Cookie: token={{token}}

### Eliminar logs por rango de fechas
DELETE {{base}}/rango?startDate=2026-04-01&endDate=2026-04-17
Cookie: token={{token}}

### Eliminar todos los logs
DELETE {{base}}/
Cookie: token={{token}}