### Variables
@baseUrl = http://localhost:3000/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXN1YXJpbyI6IkVkdWFyZG8gNDY1IiwiZW1haWwiOiJoaWFzZDEyZUBnbWFpbC5jb20iLCJyb2wiOiJBZG1pbmlzdHJhZG9yIiwiYWN0aXZvIjoxLCJpYXQiOjE3NzY0MjM2MzIsImV4cCI6MTc3OTAxNTYzMn0.SKnwwkGf_PvO8tQDssG32D9zLkRPoDRvbUIgZHmJKdM
@user_id = 8

### ─── PERFILES ───────────────────────────────────────────

### Obtener todos los perfiles
GET {{baseUrl}}/usuarios/perfiles
Authorization: Bearer {{token}}

### Obtener perfil por user_id
GET {{baseUrl}}/usuarios/perfiles/{{user_id}}
Authorization: Bearer {{token}}

### Crear perfil para un usuario
POST {{baseUrl}}/usuarios/perfiles/{{user_id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "firstName": "Juan2",
    "lastName": "Pérez2",
    "birthDate": "1999-05-15",
    "phone": "55123456782"
}

### Actualizar perfil de un usuario
PUT {{baseUrl}}/usuarios/perfiles/{{user_id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "firstName": "Juan",
    "lastName": "González",
    "birthDate": "1999-05-15",
    "phone": "5598765432"
}

### Eliminar perfil de un usuario
DELETE {{baseUrl}}/usuarios/perfiles/{{user_id}}
Authorization: Bearer {{token}}